# Generated by Django 2.0.5 on 2018-09-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180908_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
